### ISSUE TITLE
Add Website

### ISSUE THREAD

**Issue by pathologicalhandwaving** [Chobbes/org-chef#10]
I would be amazing if you would add:
The Reluctant Gourmet: - A Cooking Guide For Home Cooks
https://www.reluctantgourmet.com/

I have loads more suggestions
And here is a recipe (as per your suggestion)

* Roasted Garlic Aioli
 :PROPERTIES:
 :prep-time: 10 m
 :cook-time: 35 m
 :yield: 1 cup
 :END:

** Ingredients

- 1/2 large or one whole small head of garlic
- 1 tablespoons extra virgin olive oil
- 2 coddled egg yolks
- Pinch of salt
- Few grinds of pepper
- 2 teaspoons lemon juice
- 1/2 cup light olive oil

** Instructions

1. Preheat oven to 425 degrees.
2. Cut top off the head of garlic (not root end).
3. Place head in a small ramekin, cut side up.
4. Pour the olive oil over cut top.
5. Cover with foil and place in the oven and roast for 25-35 minutes until the garlic is soft.
6. Once cooked, pinch cooked garlic out of each clove.
7. In a food processor, place roasted garlic, coddled egg yolks, salt, pepper and lemon juice.
8. Process the mixture until smooth.
9. *Extremely slowly*, dribble oil into the processor with the motor running. It is very important that you pour the oil in very slowly to ensure proper emulsification.
10. Adjust salt and pepper to taste.

Serve at room temperature.
Keeps 5-7 days in the refrigerator.

**Comment by Chobbes** [comment]
Feel free to open more issues :).

I'll look into adding this site right away!

**Comment by Chobbes** [comment]
Should work now, let me know if you have any problems :).

Melpa may take a bit to get the new version, but next build it should work.

Thanks for the recipe by the way, I'll have to try it! :)

**Comment by pathologicalhandwaving** [comment]
Awesome!! You're amazing ty so much!
