### ISSUE TITLE
Add Website

### ISSUE THREAD

**Issue by Nelsonlittle** [Chobbes/org-chef#11]
I would like to use org-chef with the german site chefkoch.de. I tried to implement it myself but I had problems with obtaining the ingredients from the table. I think I would be able to implement the other functions. Maybe there is a german speaking developer with better Elisp and HTML skills than mine.

Example recipe
[https://www.chefkoch.de/rezepte/1108101216891426/Apfelkuchen-mit-Streuseln-vom-Blech.html](https://www.chefkoch.de/rezepte/1108101216891426/Apfelkuchen-mit-Streuseln-vom-Blech.html)

* Apfelkuchen mit Streuseln vom Blech
:PROPERTIES:
:prep-time: 30 m
:cook-time: 45 m
:END:
** Ingredients
- 300 g Mehl
- 200g Margarine oder Butter
- 100g Zucker
- 1 Ei(er)
- 1 Pck. Vanillinzucker
- 6 Äpfel, z.B. Elstar
- 350g Apfelmus
- 200g Margarine oder Butter
- 275g Mehl
- 125g Zucker
- 1TL, gestr. Zimt
- 1 Prise(n) Salz
- evtl. Walnüsse oder andere Nüsse
** Instructions
Teig: Mehl, Fett, Zucker, Ei und Vanillezucker zu einem Teig verarbeiten und auf einem Blech verteilen. Ich benutze immer ein Obstkuchenblech, das ist etwas kleiner als das übliche Blech. Dann die Äpfel schälen, in Stücke schneiden und mit dem Apfelmus in einer Schüssel vermischen. Die Masse auf den Teig geben.

Streusel: Das Fett im Topf schmelzen, vom Herd nehmen, die restlichen Zutaten vermischen und dazugeben. Diese Masse kurz abkühlen lassen und dann Streusel erzeugen, indem man Teig in die Hand nimmt und zwischen beiden Händen zerbröselt. Natürlich am besten über den Kuchen auf dem Blech.

Dann auf der mittleren Schiene bei ca. 175 Grad Heißluft ca. 45 Min. backen. Aber Vorsicht: Immer beobachten, da Streusel schnell verbrennen.

Dazu passt Sahne oder auch mal Vanilleeis. Man kann auch auf die Apfelmasse gehackte Walnüsse o. ä. geben. Und darüber dann die Streusel.

**Comment by Chobbes** [comment]
I'm not a German speaker, but I'll work on this right now! Hopefully I can get it to work for you :).

**Comment by Chobbes** [comment]
Latest version should work, at least somewhat:

https://github.com/Chobbes/org-chef/commit/f1634f471098397992e0078bbb7c347c9c2e088a

Let me know if it works / if it doesn't work!

Thanks for the suggestion :).

**Comment by Nelsonlittle** [comment]
Works perfectly! It seems to be so easy! Thank you a lot!
