### ISSUE TITLE
Marmiton recipes do not work

### ISSUE THREAD

**Issue by Bridouz** [Chobbes/org-chef#22]
Hi,

I've been using `org-chef` for a few weeks and since two or three days **Marmiton** does not work.

When I add the recipe url (e.g. https://www.marmiton.org/recettes/recette_cake-sale-aux-oignons-et-aux-lardons_23786.aspx) `emacs` says : 

```
Template is not a valid org entry or tree
```

Thanks

**Comment by Chobbes** [comment]
Hmmm that was weird!

It should be fixed now. :D
