### ISSUE TITLE
Fetching recipes from Chefkoch fails with "not an item"

### ISSUE THREAD

**Issue by michaelbogdan** [Chobbes/org-chef#34]
`M-x org-chef-insert-recipe RET https://www.chefkoch.de/rezepte/2496551392287544/Feuriger-vegetarischer-Bohneneintopf.html RET` fails with `Not an item`. 

The issue is not particular to the recipe posted, but particular to Chefkoch.de, as other websites are parsed just fine.

**Comment by michaelbogdan** [comment]
I submitted a pull request #36 to fix this.

**Comment by Chobbes** [comment]
I believe this was fixed in #36.
