### ISSUE TITLE
Add support for weber.com

### ISSUE THREAD

**Issue by mtellezj** [Chobbes/org-chef#48]
Hi, I can't parse any recipies for https://www.weber.com/ can you add it? Thanks in advance.

**Comment by egh** [comment]
see #52

**Comment by egh** [comment]
Should work in recent versions with the json-ld extractor.

**Comment by mtellezj** [comment]
Thanks, it also work with spanish recipies: https://www.weber.com/MX/es/recipes/weber-31811.html
