### ISSUE TITLE
Org-chef-edit-servings: symbol's function definition is void: reduce

### ISSUE THREAD

**Issue by Bridouz** [Chobbes/org-chef#71]
I wanted to try the new `edit-servings` but no matter what I enter it says :

`symbol's function definition is void: reduce`

I found that replacing `reduce` with `cl-reduce` in `org-chef-edit.el` fix it and I'm now able to change servings.

OS: Raspberry OS (Debian 11 ARM64)
Emacs version: 27.1

**Comment by alexhuntley** [comment]
Whoops... I must have been using `reduce` from the `cl` package by mistake...
